Imported Ubuntu patch 0.92bubuntu29

diff --git a/hook-functions b/hook-functions
--- a/hook-functions
+++ b/hook-functions
@@ -62,28 +62,23 @@ manual_add_modules()
 			continue
 		fi
 		for firmware in $firmwares; do
-			if [ -e "${DESTDIR}/lib/firmware/${firmware}" ]; then
+			if [ -e "${DESTDIR}/lib/firmware/${version}/${firmware}" ]; then
 				continue
 			fi
 
 			# Only print warning for missing fw of loaded module
 			# or forced loaded module
-			if [ ! -e "/lib/firmware/${firmware}" ]; then
+			if [ ! -e "/lib/firmware/${version}/${firmware}" ]; then
 				if grep -q "^$(basename "${mam_x}" .ko)" \
 				/proc/modules \
 				|| grep -q "^$(basename "${mam_x}" .ko)" \
 				"${CONFDIR}/modules"; then
-					echo "W: Possible missing firmware /lib/firmware/${firmware} for module $(basename ${mam_x} .ko)" >&2
+					echo "W: Possible missing firmware /lib/firmware/${version}/${firmware} for module $(basename ${mam_x} .ko)" >&2
 				fi
 				continue
 			fi
 
-			if [ ! -e "${DESTDIR}/lib/udev/firmware.agent" ] \
-			&& [ -e "/lib/udev/firmware.agent" ]; then
-				copy_exec /lib/udev/firmware.agent
-			fi
-
-			copy_exec "/lib/firmware/${firmware}"
+			copy_exec "/lib/firmware/${version}/${firmware}"
 			if [ "${verbose}" = "y" ]; then
 				echo "Adding firmware ${firmware}"
 			fi
@@ -146,8 +141,9 @@ copy_exec() {
 	    s/[[:blank:]]*\([^[:blank:]]*\) (.*)/\1/' 2>/dev/null); do
 
 		# Try to use non-optimised libraries where possible.
-		# We assume that all HWCAP libraries will be in tls.
-		nonoptlib=$(echo "${x}" | sed -e 's#/lib/\(tls\|i686\).*/\(lib.*\)#/lib/\2#')
+		# We assume that all HWCAP libraries will be in tls,
+		# sse2, vfp or neon
+		nonoptlib=$(echo "${x}" | sed -e 's#/lib/\(tls\|i686\|sse2\|neon\|vfp\).*/\(lib.*\)#/lib/\2#')
 
 		if [ -e "${nonoptlib}" ]; then
 			x="${nonoptlib}"
@@ -315,13 +311,18 @@ auto_add_modules()
 {
 	case "$1" in
 	base)
-		for x in ehci-hcd ohci-hcd uhci-hcd usbhid usb-storage ext2 \
-		ext3 isofs jfs nfs reiserfs xfs af_packet atkbd i8042; do
+		for x in ehci-hcd ohci-hcd uhci-hcd usbhid hid_a4tech \
+		hid_apple hid_belkin hid_bright hid_cherry hid_chicony \
+		hid_cypress hid_dell hid_ezkey hid_gyration hid_logitech \
+		hid_microsoft hid_monterey hid_petalynx hid_pl 	hid_samsung \
+		hid_sony hid_sunplus hid_tmff hid_zpff usb-storage ext2 \
+		ext3 ext4 isofs jfs nfs reiserfs udf xfs af_packet atkbd i8042 \
+		virtio_pci vfat nls_cp437 nls_iso8859-1; do
 			manual_add_modules "${x}"
 		done
 	;;
 	net)
-		for x in 3c59x 8139cp 8139too 8390 atl1 b44 bmac \
+		for x in 3c59x 8139cp 8139too 8390 atl1 atl1e b44 bmac \
 		bnx2 cxgb3 defxx dl2k e100 e1000 e1000e ehea epic100 \
 		ep93xx_eth eql fealnx famachi forcedeth gelic_net \
 		hp100 igb ipg mace mv643xx_eth myri10ge \
diff --git a/scripts/local b/scripts/local
--- a/scripts/local
+++ b/scripts/local
@@ -11,6 +11,11 @@ get_fstype ()
 	# vol_id has a more complete list of file systems,
 	# but fstype is more robust
 	eval $(fstype "${FS}" 2> /dev/null)
+
+	if [ -z "${FSTYPE}" ]; then
+		FSTYPE="unknown"
+	fi
+
 	if [ "$FSTYPE" = "unknown" ] && [ -x /lib/udev/vol_id ]; then
 		FSTYPE=$(/lib/udev/vol_id -t "${FS}" 2> /dev/null)
 	fi
@@ -24,6 +29,12 @@ get_fstype ()
 	return ${RET}
 }
 
+root_missing()
+{
+	ROOT="${1}"
+	[ ! -e "${ROOT}" ] || ! $(get_fstype "${ROOT}" >/dev/null) || ! /sbin/udevadm settle
+}
+
 # Parameter: Where to mount the filesystem
 mountroot ()
 {
@@ -33,12 +44,12 @@ mountroot ()
 
 	# If the root device hasn't shown up yet, give it a little while
 	# to deal with removable devices
-	if [ ! -e "${ROOT}" ] || ! $(get_fstype "${ROOT}" >/dev/null); then
+	while root_missing "${ROOT}"; do
 		log_begin_msg "Waiting for root file system..."
 
-		# Default delay is 180s
+		# Default delay is 30s
 		if [ -z "${ROOTDELAY}" ]; then
-			slumber=180
+			slumber=30
 		else
 			slumber=${ROOTDELAY}
 		fi
@@ -47,8 +58,7 @@ mountroot ()
 		fi
 
 		slumber=$(( ${slumber} * 10 ))
-		while [ ! -e "${ROOT}" ] \
-		|| ! $(get_fstype "${ROOT}" >/dev/null); do
+		while root_missing "${ROOT}"; do
 			/bin/sleep 0.1
 			slumber=$(( ${slumber} - 1 ))
 			[ ${slumber} -gt 0 ] || break
@@ -62,10 +72,17 @@ mountroot ()
 		if [ -x /sbin/usplash_write ]; then
 			/sbin/usplash_write "TIMEOUT 15" || true
 		fi
-	fi
+
+		# Run failure hooks, hoping one of them can fix up the system
+		# and we can restart the wait loop.  If they all fail, abort
+		# and move on to the panic handler and shell.
+		if root_missing "${ROOT}" && ! try_failure_hooks; then
+			break
+		fi
+	done
 
 	# We've given up, but we'll let the user fix matters if they can
-	while [ ! -e "${ROOT}" ]; do
+	while root_missing "${ROOT}"; do
 		# give hint about renamed root
 		case "${ROOT}" in 
 		/dev/hd*)
@@ -85,9 +102,12 @@ mountroot ()
 			fi
 			;;
 		esac
-		echo "ALERT!  ${ROOT} does not exist.  Dropping to a shell!"
-		echo "	Check your root= boot argument (cat /proc/cmdline)"
-		panic "	Check for missing modules (cat /proc/modules), or device files (ls /dev)"
+		echo "Gave up waiting for root device.  Common problems:"
+		echo " - Boot args (cat /proc/cmdline)"
+		echo "   - Check rootdelay= (did the system wait long enough?)"
+		echo "   - Check root= (did the system wait for the right device?)"
+		echo " - Missing modules (cat /proc/modules; ls /dev)"
+		panic "ALERT!  ${ROOT} does not exist.  Dropping to a shell!"
 	done
 
 	# Get the root filesystem type if not set
@@ -101,7 +121,8 @@ mountroot ()
 	run_scripts /scripts/local-premount
 	[ "$quiet" != "y" ] && log_end_msg
 
-	if [ "${readonly}" = "y" ]; then
+	if [ ${readonly} = y ] && \
+	   [ -z "$LOOP" ]; then
 		roflag=-r
 	else
 		roflag=-w
@@ -113,6 +134,58 @@ mountroot ()
 	# FIXME This has no error checking
 	# Mount root
 	mount ${roflag} -t ${FSTYPE} ${ROOTFLAGS} ${ROOT} ${rootmnt}
+	mountroot_status="$?"
+	if [ "$LOOP" ]; then
+		if [ "$mountroot_status" != 0 ]; then
+			if [ ${FSTYPE} = ntfs ] || [ ${FSTYPE} = vfat ]; then
+				panic "
+Could not mount the partition ${ROOT}.
+This could also happen if the file system is not clean because of an operating
+system crash, an interrupted boot process, an improper shutdown, or unplugging
+of a removable device without first unmounting or ejecting it.  To fix this,
+simply reboot into Windows, let it fully start, log in, run 'chkdsk /r', then
+gracefully shut down and reboot back into Windows. After this you should be
+able to reboot again and resume the installation.
+(filesystem = ${FSTYPE}, error code = $mountroot_status)
+"
+			fi
+		fi
+	
+		mkdir -p /host
+		mount -o move ${rootmnt} /host
+
+		while [ ! -e "/host/${LOOP#/}" ]; do
+			panic "ALERT!  /host/${LOOP#/} does not exist.  Dropping to a shell!"
+		done
+
+		# Get the loop filesystem type if not set
+		if [ -z "${LOOPFSTYPE}" ]; then
+			eval $(fstype < "/host/${LOOP#/}")
+		else
+			FSTYPE="${LOOPFSTYPE}"
+		fi
+		if [ "$FSTYPE" = "unknown" ] && [ -x /lib/udev/vol_id ]; then
+			FSTYPE=$(/lib/udev/vol_id -t "/host/${LOOP#/}")
+			[ -z "$FSTYPE" ] && FSTYPE="unknown"
+		fi
+
+		if [ ${readonly} = y ]; then
+			roflag=-r
+		else
+			roflag=-w
+		fi
+
+		# FIXME This has no error checking
+		modprobe loop
+		modprobe ${FSTYPE}
+
+		# FIXME This has no error checking
+		mount ${roflag} -o loop -t ${FSTYPE} ${LOOPFLAGS} "/host/${LOOP#/}" ${rootmnt}
+
+		if [ -d ${rootmnt}/host ]; then
+			mount -o move /host ${rootmnt}/host
+		fi
+	fi
 
 	[ "$quiet" != "y" ] && log_begin_msg "Running /scripts/local-bottom"
 	run_scripts /scripts/local-bottom
