mkininitramfs: MODULES=dep fallback to /proc/mounts for rootdev
mount output may not contain proper rootdev on some funky aufs setups:

aufs on / type aufs (rw)

"root is on a usb-flash-disk, in normal operation root is on an aufs,
to prevent to many writes to the flash.
for the dist-upgrade the box was booted without the bootarg
aufs=tmpfs."

Thus if mount parsing shows nothing, try /proc/mounts as fallback.

Closes: #600453
Reported-by: kurt witschi <tmpml@gmx.net>
Tested-by: kurt witschi <tmpml@gmx.net>
Signed-off-by: maximilian attems <max@stro.at>

diff --git a/hook-functions b/hook-functions
--- a/hook-functions
+++ b/hook-functions
@@ -226,10 +226,18 @@ dep_add_modules()
 
 	# findout root block device + fstype
 	eval "$(mount | awk '/\/dev\// {if ($3 == "/") {print "root=" $1 "\nFSTYPE=" $5; exit}}')"
+
+	# On failure fallback to /proc/mounts if readable
+	if [ -z "$root" ] && [ -r /proc/mounts ]; then
+		eval "$(awk '/\/dev\// {if ($2 == "/") {print "root=" $1 "\nFSTYPE=" $5; exit}}' /proc/mounts)"
+	fi
+
+	# recheck root device
 	if [ -z "$root" ]; then
 		echo "mkinitramfs: failed to determine root device" >&2
 		echo "mkinitramfs: workaround is MODULES=most" >&2
-		echo "Error please report bug on initramfs-tools and include the output of 'mount'" >&2
+		echo "Error please report bug on initramfs-tools" >&2
+		echo "Include the output of 'mount' and 'cat /proc/mounts'" >&2
 		exit 1
 	fi
 
