Produce an error when root cannot be determined with MODULES=dep
A lot of code in dep_add_modules() uses $root.  Therefore, produce an
error message if we cannot determine the root device.

[ error out on this condtion too. -maks ]

Signed-off-by: Martin Michlmayr <tbm@cyrius.com>
Signed-off-by: maximilian attems <maks@debian.org>

diff --git a/hook-functions b/hook-functions
--- a/hook-functions
+++ b/hook-functions
@@ -226,6 +226,12 @@ dep_add_modules()
 
 	# findout root block device + fstype
 	eval "$(mount | awk '/\/dev\// {if ($3 == "/") {print "root=" $1 "\nFSTYPE=" $5; exit}}')"
+	if [ -z "$root" ]; then
+		echo "mkinitramfs: failed to determine root device"
+		echo "mkinitramfs: workaround is MODULES=most"
+		echo "Error please report bug on initramfs-tools and include the output of 'mount'"
+		exit 1
+	fi
 
 	# handle ubifs and return since ubifs root is a char device but
 	# most of the commands below only work with block devices.
