lsinitramfs: be more defensive against cmdline options
* make sure the specified file(s) can be read
* redirect error message to stderr
* support -h/--help option
* variable quoting

Signed-off-by: Michael Prokop <mika@debian.org>

diff --git a/lsinitramfs b/lsinitramfs
--- a/lsinitramfs
+++ b/lsinitramfs
@@ -3,12 +3,24 @@
 usage()
 {
 	echo "Usage: $(basename $0) <initramfs file>"
-	exit 1
 }
 
-[ $# -eq 0 ] && usage
+if [ "$#" -eq 0 ] ; then
+	usage >&2
+	exit 1
+fi
 
-for i in $*; do
-	echo $i
-	zcat $i | cpio --extract --verbose --quiet --list
+if [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
+	usage
+	exit 0
+fi
+
+for i in "$*" ; do
+	if ! [ -r "$i" ] ; then
+		echo "Specified file could not be read." >&2
+		exit 1
+	else
+		echo "$i"
+		zcat "$i" | cpio --extract --verbose --quiet --list
+		fi
 done
