mkinitramfs: Provide error code of failed mkinitramfs creation
We better print them out before exiting, this should allow
quicker diagnose of what is going on.

Be sure to print out all error codes as a failure of compress
is highly likely to generate an SIGPIPE aka error code 141.
Silent error exits are troublesome for debugging error cause.

Signed-off-by: maximilian attems <maks@debian.org>

diff --git a/mkinitramfs b/mkinitramfs
--- a/mkinitramfs
+++ b/mkinitramfs
@@ -327,9 +327,18 @@ eval `
 	} | "${compress}" >"${outfile}"
 	echo "ec3=$?;" >&4
 `
-if [ "$ec1" -ne 0 ]; then exit "$ec1"; fi
-if [ "$ec2" -ne 0 ]; then exit "$ec2"; fi
-if [ "$ec3" -ne 0 ]; then exit "$ec3"; fi
+if [ "$ec1" -ne 0 ]; then
+	echo "E: mkinitramfs failure find $ec1 cpio $ec2 $compress $ec3"
+	exit "$ec1"
+fi
+if [ "$ec2" -ne 0 ]; then
+	echo "E: mkinitramfs failure cpio $ec2 $compress $ec3"
+	exit "$ec2"
+fi
+if [ "$ec3" -ne 0 ]; then
+	echo "E: mkinitramfs failure $compress $ec3"
+	exit "$ec3"
+fi
 ) || exit 1
 
 if [ -s "${__TMPCPIOGZ}" ]; then
