jonas: use gnu getopt instead of getopts

diff --git a/mkinitramfs b/mkinitramfs
--- a/mkinitramfs
+++ b/mkinitramfs
@@ -10,26 +10,46 @@ errors_to="2>/dev/null"
 # BUSYBOXDIR="/usr/lib/initramfs-tools/bin/"
 BUSYBOXDIR="/bin" 
 
-while getopts "d:ko:r:" flag; do
-	case $flag in
-	d)
-		CONFDIR="${OPTAGS}"
+OPTIONS=`getopt -o d:ko:r: -n "$0" -- "$@"`
+
+# Check for non-GNU getopt
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+
+eval set -- "$OPTIONS"
+
+while true; do
+	case "$1" in
+	-d)
+		CONFDIR="$2"
+		shift 2
 		if [ ! d "${CONFDIR}" ]; then
 			echo "${0}: ${CONFDIR}: Not a directory" >&2
 			exit 1
 		fi
 		;;
-	o)
-		touch ${OPTARG}
-		outfile="$(readlink -f ${OPTARG})"
+	-o)
+		touch $2
+		shift $2
+		outfile="$(readlink -f $2)"
 		;;
-	k)
+	-k)
 		keep="y"
+		shift
+		;;
+	-r)
+		# ignore (FIXME: manpage says differently?!?)
+		shift 2
+		;;
+	--)
+		shift
+		break
+		;;
+	*)
+		echo "Internal error!" >&2
+		exit 1
 		;;
 	esac
 done
-
-shift $((${OPTIND} - 1))
 
 # For dependency ordered mkinitramfs hook scripts.
 . /usr/share/initramfs-tools/scripts/functions
