scripts/functions: add get_fstype() from scripts/local
allows wider usage.

(closes: #487409)

Reported-by: Christoph Anton Mitterer <calestyo@scientia.net>
Signed-off-by: maximilian attems <maks@debian.org>

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -256,6 +256,32 @@ parse_numeric() {
 	ROOT=/dev/root
 }
 
+# Parameter: device node to check
+# Echos fstype to stdout
+# Return value: indicates if an fs could be recognized
+get_fstype ()
+{
+	local FS FSTYPE FSSIZE RET
+	FS="${1}"
+
+	# vol_id has a more complete list of file systems,
+	# but fstype is more robust
+	eval $(fstype "${FS}" 2> /dev/null)
+	if [ "$FSTYPE" = "unknown" ] &&  command -v blkid >/dev/null 2>&1 ; then
+		FSTYPE=$(blkid -o value -s TYPE "${FS}")
+	elif [ "$FSTYPE" = "unknown" ] && [ -x /lib/udev/vol_id ]; then
+		FSTYPE=$(/lib/udev/vol_id -t "${FS}" 2> /dev/null)
+	fi
+	RET=$?
+
+	if [ -z "${FSTYPE}" ]; then
+		FSTYPE="unknown"
+	fi
+
+	echo "${FSTYPE}"
+	return ${RET}
+}
+
 configure_networking()
 {
 	if [ -n "${BOOTIF}" ]; then
